aws_region          = "us-east-1"
environment         = "dev"
project_name        = "my-eks"
cluster_name        = "my-eks-cluster"
vpc_cidr            = "10.0.0.0/16"
cluster_version     = "1.36"
node_count          = 2
node_instance_type  = "t3.medium"
disk_size           = 50
public_access_cidrs = ["YOUR_IP_ADDRESS/32"]  # Replace with your IP address
